### ISSUE TITLE
Create deploy script to generate API cache 

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-web#208]
## Context

We need to create a deploy script that captures some sensible default information for graceful operation during API outage.

This issue is the refactoring of created PR https://github.com/AlexsLemonade/refinebio-web/pull/164 (issue https://github.com/AlexsLemonade/refinebio-web/issues/163).

## Problem or idea

Ideally we would be fetching these stats in real time but they can be expensive and/or fail.
We should start by creating the deploy script and committing the initial cache json to VC.

## Solution or next step

- Implement script that writes cached requests to a json file.
- include the generated cache file

**Comment by nozomione** [comment]
## Overview of API cache usage

This is a breakdown of the usage of the API cache deploy script (based on the current implementation) in our application.

**NOTE:** Each resource's Django view (from [`refinebio`](https://github.com/AlexsLemonade/refinebio)) is linked for quick reference.

### Resources
We fetch these resources at pre-build instead of at rumtime, since they can be expensive and/or fail.
<Table>
<thead>
  <tr>
    <th>Name</th>
    <th>Return Value</th>
    <th>Usage</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><a href="https://github.com/AlexsLemonade/refinebio/blob/dev/api/data_refinery_api/views/platform.py"><code>platforms</code></a></td>
    <td valign="top">
      <p>We fetch the following resources:</p>
      <p><strong>Resource 1:</strong> An unpaginated list of all available platform information.</p>
     <p><strong>Resource 2:</strong> The current API version - a value of the <code>X-Source-Revision</code> field in the response headers (e.g., v1.45.27-hotfix).</p>
      e.g.) The platform information for <code>ovigene10st</code>:
      <div>
      <pre>
  { 
    platform_accession_code:"ovigene10st", 
    platform_name:"[OviGene-1_0-st] Ovine Gene 1.1 ST Array" 
  }
      </pre>
      </div> 
    </td>
   <td valign="top">
      <p><strong>Resource 1</strong> is used to display platform names for the platform in facets on search results page and is necessary since the search endpoint returns platform accession codes only which are not user-friendly.</p>
      <p><strong>Resource 2</strong> is used in the site footer. It's also used in the regenerate dataset view on the dataset page to display a message "Some expression values may differ." when the worker version of that dataset doesn't match this current API version.</p>
      <p><strong>Components:</strong> <code>SearchResults/SearchFilter</code>, <code>Footer</code></p>
    </td>
  </tr>
  <tr>
    <td><a href="https://github.com/AlexsLemonade/refinebio/blob/dev/api/data_refinery_api/views/qn_targets.py"><code>qn_targes</code></a></td>
    <td valign="top">
      <p>We fetch an unpaginated list of all of the organisms which have available QN Targets and format it for UI.</p>
      e.g.)
      <div>
      <pre>
// the API response
[
 {
   name:"MUSCULUS"
   taxonomy_id:112137
 },
 {
   name:"VITIS_RIPARIA",
   taxonomy_id:96939
 }, 
 ...
]
// the formatted API response data structure
{ 
 [name]: true,
 ...
}
      </pre>
      </div>  
    </td>
    <td valign="top"><p>This is used in the samples table for samples that cannot be processed to display a message and provide a link to our doc's FAQ page (<a href="https://docs.refine.bio/en/latest/faq.html#why-can-t-i-add-certain-samples-to-my-dataset">Why can’t I add certain samples to my dataset?</a>).</p>
    <p><strong>Component:</strong> <code>SamplesTable/AddRemoveCell</code></p>
    </td>
  </tr>
  <tr>
    <td><a href="https://github.com/AlexsLemonade/refinebio/blob/517b27676a37b6d14158d7c65c5bc37e6e705e5f/api/data_refinery_api/views/stats.py#L464C2-L464C2"><code>stats-about</code></a></td>
    <td valign="top">
     <p>We fetch the general stats of the site that is used in the about page.</p>
      e.g.)
      <div>
      <pre>
  {
    samples_available:1361305,
    total_size_in_bytes:844873585400894,
    supported_organisms:203,
    experiments_processed:46382
  }  
      </pre>
      </div>
    </td>
    <td valign="top"><p>This is used to display the general stats in the hero on the about page.</p>
   <p><strong>Component:</strong> <code>About/Hero</code></p>
    </td>
  </tr>
</tbody>
</Table>

### Process for generating API cache

The latest copy of the API cache is generated on pre-build by executing the API cache script (`src/cacheAPI.js`) and is outputted to `src/config/apiCache.json` which is then imported into the required components listed above.

e.g. ) The cache used in the `Footer` component:

```js
// Footer component
import { cache } from 'config'

// in JSX
{cache.version && cache.xSourceRevision && (
  <Box>
    <Text>
      Version {cache.xSourceRevision} - {cache.version.slice(1)}
    </Text>
 </Box>
)}
```

## Next Steps
Let me know your thoughts on this and let's outline the details of new strategies/implementation to improve the existing one (PR https://github.com/AlexsLemonade/refinebio-web/pull/164) 👍

**Comment by nozomione** [comment]
@davidsmejia I resolved the merge conflicts in PR https://github.com/AlexsLemonade/refinebio-web/pull/164 and is now ready for your review. I also updated our "Next Step" according to our 1:1 chat, thank you.

**Comment by nozomione** [comment]
🗒️  Closing - the generated API cache file has been committed to the `dev` branch and all items in the next steps were completed, thank you ✅
